import {create} from "zustand";

const useFormPesertaDidikStore = create((set) => ({
    sekolah_id:localStorage.getItem("sekolah_id"),
    nama:null,
    jenis_kelamin:null,
    tempat_lahir:null,
    tanggal_lahir:null,
    agama_id:null,
    kewarganegaraan:null,
    nisn:null,
    nipd:null,
    golongan_darah:null,
    alat_transportasi_id:null,
    anak_keberapa:null,
    jumlah_saudara_kandung:null,
    nama_ayah:null,
    pendidikan_ayah_id:null,
    pekerjaan_ayah_id:null,
    tanggal_lahir_ayah:null,
    nama_ibu_kandung:null,
    pendidikan_ibu_id:null,
    pekerjaan_ibu_id:null,
    tanggal_lahir_ibu:null,
    nama_wali:null,
    pendidikan_wali_id:null,
    pekerjaan_wali_id:null,
    tanggal_lahir_wali:null,
    nik:null,
    no_kk:null,
    reg_akta_lahir:null,
    no_kks:null,
    penerima_kps:null,
    no_kps:null,
    penerima_kip:null,
    layak_pip:null,
    alasan_layak_pip:null,
    no_kip:null,
    nama_di_kip:null,
    npsn_jenjang_sebelumnya:null,
    penerima_pip:null,
    jenis_tinggal:null,
    tmt:null,

    setform:(name,value) => set(() => ({[name]: value})),
    resetform:() => set(() => ({
        sekolah_id:localStorage.getItem("sekolah_id"),
        nama:null,
        jenis_kelamin:null,
        tempat_lahir:null,
        tanggal_lahir:null,
        agama_id:null,
        kewarganegaraan:null,
        nisn:null,
        nipd:null,
        golongan_darah:null,
        alat_transportasi_id:null,
        anak_keberapa:null,
        jumlah_saudara_kandung:null,
        nama_ayah:null,
        pendidikan_ayah_id:null,
        pekerjaan_ayah_id:null,
        tanggal_lahir_ayah:null,
        nama_ibu_kandung:null,
        pendidikan_ibu_id:null,
        pekerjaan_ibu_id:null,
        tanggal_lahir_ibu:null,
        nama_wali:null,
        pendidikan_wali_id:null,
        pekerjaan_wali_id:null,
        tanggal_lahir_wali:null,
        nik:null,
        no_kk:null,
        reg_akta_lahir:null,
        no_kks:null,
        penerima_kps:null,
        no_kps:null,
        penerima_kip:null,
        layak_pip:null,
        alasan_layak_pip:null,
        no_kip:null,
        nama_di_kip:null,
        npsn_jenjang_sebelumnya:null,
        penerima_pip:null,
        jenis_tinggal:null,
        tmt:null,

    }))
}))

export default useFormPesertaDidikStore